<a href="https://colab.research.google.com/github/AWS-MLAI/AWS-Cloud-Cloud-PUP-Manila-ML-AI/blob/master/Workshop%231_assets/Workshop_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to AWS Department in Machine Learning/Artificial Intelligence:

<div style="display: flex; justify-content: center; align-items: center;">
  <img src="https://github.com/AWS-MLAI/AWS-Cloud-Cloud-PUP-Manila-ML-AI/blob/master/Miscellaneous/aws%20logo.jpg?raw=true" width="300">
</div>


## For our first workshop we are going to be introducing:

* Python and its syntaxes
* Common Python libraries used in Data processing, Data analyzation, and Machine Learning in general.

## Python

<div style="display: flex; justify-content: center; align-items: center;">
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/800px-Python-logo-notext.svg.png" width="300">
</div>

### Now, you might ask.
# WHY PYTHON?
* Python is a great idea to learn machine learning because it gives you flexibility since its syntax is clean and relatively easier to understand because of its "straightfowardness" nature of it.
* Python has a great "ecosystem" of libraries and frameworks, meaning it has tons of ready-to-use tools that would make your life easier building machine learning models.
* Almost all of Machine learning Engineers frequently use Python to build their ML/AI Models, which is why it has a large community of developers and data scientists that are still continuing to improve its "libraries" or tools.

### Variable Declaration
#### As opposed to the C language, we can just straightfowardly declare the variable and assign it a value.
#### Example:
|**Data Type**|**C**|**Python**|
|-----|-----|-----|
|**Integer**|int x = 5;|x = 5|
|**Float**|float y = 3.14;| y = 3.14|
|**Character**|char ch = 'A';| ch = 'a'|
|**String**|char str[] = "AWS PUP"; **or** char str[] = {'A', 'W', 'S', ' ', 'P', 'U', 'P', '\0'}; |string = "AWS PUP"|
|**Integer Array**|int intArr[5] = {1, 2, 3, 4, 5};|intArr = [1, 2, 3, 4, 5]|
|**Float Array**|float floatArr[5] = {1.1, 2.2, 3.3, 4.4, 5.5};|floatArr = [1.1, 2.2, 3.3, 4.4, 5.5]|
|**String Array**|char strArr[][12] = {"AWS", "PUP", "MANILA"};|strArr = ["AWS", "PUP", "MANILA"]|

In [ ]:
# Variable Declaration

# Integer
x = 5

# Float
y = 5.5

# Character
ch = 'A'

# String
string = "AWS PUP MANILA"

# Integer Array
intArr = [1, 2, 3, 4, 5]

# Float Array
floatArr = [1.1, 2.2, 3.3, 4.4, 5.5]

# String Array
strArr = ["AWS", "PUP", "MANILA"]

### Print statement
#### Just like in C, you can format your print command in python, for example:
|**C**|**Python**|
|-----|-----|
|**`printf("My name is %s and I am %d years old\n", myName, myAge);`**|**`print(f"My name is {myName} and I am {myAge} years old")`**|


In [ ]:
myName = "Mark Macaraeg"
myAge = 20

print(f"My name is {myName} and I am {myAge} years old")

My name is Mark Macaraeg and I am 20 years old


### But unlike in C, you can directly print your array in Python, for example:
#### Command: `print(intArray)`
#### Output: `[1, 2, 3, 4, 5]`

In [ ]:
# Array of Integers
intArr = [2, 0, 2, 4]
print(intArr)

# Array of Strings
strArr = ["AWS", "PUP", "MANILA"]
print(strArr)

[2, 0, 2, 4]
['AWS', 'PUP', 'MANILA']


##### And like in C, or in many programming languages, index 0 is used to access the first element of a list
#####`intArr = [2, 0, 3, 4]`
#####`print(intArr[0])`
##### output: 2

In [ ]:
intArr = [2, 0, 3, 4]
print(intArr[0])

2


## Basic Arithmetic Operations:
### `addition = 1 + 1`
### `subtraction = 10 - 5`
### `multiplication = 5 * 5`
### `division = 10/3`

In [ ]:
addition = 1 + 1
subtraction = 10 - 5
multiplication = 5 * 5
division = 10/3

print(f"Addition result: {addition}")
print(f"Subtraction result: {subtraction}")
print(f"Multiplication result: {multiplication}")
print(f"Division result: {division:.2f}") # `.2f` means to limit the number of decimal places to two in Python.

Addition result: 2
Subtraction result: 5
Multiplication result: 25
Division result: 3.33


## Conditional statements using `if`, `elif`, `else` for decision making

In [ ]:
given_number = 42
number_to_compare = 167

if given_number > number_to_compare:
  print(f"Your given number {given_number} is greater than {number_to_compare}")
elif given_number == number_to_compare:
  print(f"Your given number {given_number} is equal to {number_to_compare}")
else:
  print(f"Your given number {given_number} is less than {number_to_compare}")

Your given number 42 is less than 167


# Loops using `for` loops and `while` loops

In [ ]:
print("For loop Example: ")
# For loop
for i in range(10): # iterate 10 times
    print(i)

print("\n") # Print a new line

print("While loop Example: ")
# While loop
count = 0
while count < 10:
    print(count)
    count += 1


For loop Example: 
0
1
2
3
4
5
6
7
8
9


While loop Example: 
0
1
2
3
4
5
6
7
8
9


## Iterate each element in a list

In [ ]:
my_list = ["AWS", "PUP", "MANILA"]

for element in my_list:
  print(element)

AWS
PUP
MANILA


## P.S. While Python syntax may seem easy, keep in mind that Python is VERY sensitive to indentation.

In [ ]:
# Example of indentation error in Python

my_numbers = [1, 2, 3, 4, 5]

for number in my_numbers:
  if number % 2 == 0:
  print(f"{number} is an even number") # Cause of error: Lack of indentation
  else:
  print(f"{number} is not an even number")

IndentationError: expected an indented block after 'if' statement on line 6 (<ipython-input-41-e797f2c8f0d3>, line 7)

In [ ]:
# Same code but with appropriate indentations

my_numbers = [1, 2, 3, 4, 5]

for number in my_numbers:
  if number % 2 == 0:
    print(f"{number} is an even number")
  else:
    print(f"{number} is not an even number")


1 is not an even number
2 is an even number
3 is not an even number
4 is an even number
5 is not an even number


# Function declaration structure:

<div style="display: flex; justify-content: center; align-items: center;">
  <img src = "https://github.com/AWS-MLAI/AWS-Cloud-Cloud-PUP-Manila-ML-AI/blob/master/Workshop%231_assets/def%20function_name.png?raw=true" width="500">
</div>

In [ ]:
# Create a function that adds two numbers that returns the sum.

def add(number_1, number_2):
  sum = number_1 + number_2
  return sum

result = add(5, 3)
result

8

# Now let's move on to some libraries commonly used in Data processes and Machine learning
### But, before that, what's a library?
* A library is a collection of codes that developers have created, or in other words, "pre-written codes" that we can reuse to solve a problem. So imagine it like a toolbox, which makes your life easier building things in your code.
* It can contain lots of functions, such as a function to add two numbers like what we declared above.
* It can also contain classes, which is a blueprint for creating something like a "Person" where it can contain methods (or functions) like eating, walking, breathing, and attributes (or variables) like height, weight, and age.

### Now, let's get into it by starting with "NumPy"

<div style = "display: flex; justify-content: center; align-items: center;">
  <img src = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1200px-NumPy_logo_2020.svg.png" width="400">

</div>

### What's NumPy?
#### NumPy, short for Numerical Python, is a package or a library that can deal with numerical computations, which can speed things up for you if you want to solve mathematical problems, like dealing with arrays of numbers, matrices, or anything that involves huge amount of numbers. In other words, NumPy arrays can perform complex mathematical operations on **veeerryyy** big data more efficiently and with less code than Python's built-in lists, which is why many developers like Machine Learning engineers are in love with NumPy.
#### Furthermore, it contains functions or tools related to Math, like trigonometry, exponential functions, logarithmic functions, and more.
#### Visit https://numpy.org/doc/stable/user/index.html for its documentation.
## Advantages of NumPy over normal Python Lists
* Efficient memory usage because NumPy arrays store elements of the same data type, whereas Python lists can contain elements of different data types. And because NumPy arrays store data in a contiguous (in adjacent) block of memory.
* It can integrate well with other libraries and tools used in Data processing and Machine learning ecosystem, such as Pandas, Matplotlib, and scikit-learn.
* It allows you to easily do arethmetic operations with every element in an array (also known as element-wise operations), which makes it easy and very fast to do maths with the entire array because it uses something called "vectorized operations".

In [ ]:
# Let's get started with NumPy!

import numpy as np # as np is just a shortcut word to access the package's tools

# Create a 1D array of many zeros as you like
zeros_1d = np.zeros(10)
print(f"1D Array filled with zeros: \n{zeros_1d}")



# Create a 2D array (matrix) of many zeros as you like
zeros_2d = np.zeros((2, 5)) # In this case, we created a 2x5 zeros
print(f"2D Array filled with zeros: \n{zeros_2d}\n")


# Create a 1D array of many ones as you like
ones_1d = np.ones(10)
print(f"1D Array filled with ones: \n{ones_1d}")



# Create a 2D array (matrix) of many ones as you like
ones_2d = np.ones((2, 5)) # In this case, we created a 2x5 ones
print(f"2D Array filled with ones: \n{ones_2d}\n")


# Fill a 1D array of a specific value as you like
specific_value = 42
full_1d = np.full((10), specific_value)
print(f"1D Array filled with 10: \n{full_1d}")



# Fill a 2D array (matrix) of a specific value as you like
full_2d = np.full((2,5), specific_value)
print(f"2D Array filled with 10: \n{full_2d}\n")




1D Array filled with zeros: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2D Array filled with zeros: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

1D Array filled with ones: 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
2D Array filled with ones: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

1D Array filled with 10: 
[42 42 42 42 42 42 42 42 42 42]
2D Array filled with 10: 
[[42 42 42 42 42]
 [42 42 42 42 42]]



##### Check whether a value is a NaN or inf

In [ ]:
import numpy as np

nan_value = np.NaN # Assign a NaN value to variable `nan_value`
if np.isnan(nan_value) == True:
  print("The variable nan_value contains NaN value")

inf_value = np.inf # Assign a inf value to variable `inf_value`
if np.isinf(inf_value) == True:
  print("The variable inf_value contains inf value")


The variable nan_value contains NaN value
The variable inf_value contains inf value


##### Create arrays using NumPy

In [ ]:
import numpy as np
# Create an array using numpy
numpy_array = np.array([1, 2, 3])
print(f"My array: \n{numpy_array}\n")

# Create a 2D matrix using numpy
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(f"My matrix (2D array): \n{matrix}\n")


# Create an array with a starting number and an ending number with a specific steps
starting_number = 0
ending_number = 42
steps = 2
arrays_with_arange = np.arange(start=starting_number,
                                 stop=ending_number,
                                 step=steps)
print(f"Arrays using .arange() with start={starting_number}, stop={ending_number}, and step={steps}: \n{arrays_with_arange}\n")

# You can use a function similar to `np.arange`, called `np.linspace` except instead of using intervals for `step`, we use the `num` argument to specify how many values to generate over a specified interval[start, stop].
starting_number = 0
ending_number = 42
amount_to_generate = 10
arrays_with_linspace = np.linspace(start=starting_number,
                                   stop=ending_number,
                                   num=amount_to_generate)
print(f"Arrays using .linspace() with start={starting_number}, stop={ending_number}, and num={amount_to_generate}: \n{arrays_with_linspace}\n")

My array: 
[1 2 3]

My matrix (2D array): 
[[1 2 3]
 [4 5 6]]

Arrays using .arange() with start=0, stop=42, and step=2: 
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]

Arrays using .linspace() with start=0, stop=42, and num=10: 
[ 0.          4.66666667  9.33333333 14.         18.66666667 23.33333333
 28.         32.66666667 37.33333333 42.        ]



#### Create random values in arrays with NumPy

In [ ]:
# What if I want to randomly generate integers with a given shape and upper bound(limit)?
upper_bound = 6 # meaning generate a numbers either 0 up to upper_bound-1  only, in this case, it will generate numbers either 0 - 5 only
size_1 = 2
size_2 = 5
random_array = np.random.randint(upper_bound, size=(size_1, size_2))
print(f"My random array: \n{random_array}\n")


# Create an array with values between 0 and 1. In technical terms, create random samples from a uniform distribution over [0, 1).
random_distribution = np.random.rand(2, 5) # The reason why we're doing this is, because these values are very commonly used in Machine learning.
print(f"My random array with range between 0 and 1: \n{random_distribution}\n")


# Convert an array with a specific datatype to another.
low = 0 # basically just the lower bound
high = 6 # basically just the upper bound
random_uniform_array = np.random.uniform(low, high, size=(2, 5)) #
random_uniform_array_transformed = random_uniform_array.astype(np.intc) # .astype(np.intc) means to convert the values of the array into integers
print(f"Random array before converting datatype: \n{random_uniform_array}")
print(f"Random array after converting datatype: \n{random_uniform_array_transformed}")

NameError: name 'np' is not defined

## Processing arrays in NumPy

#### Using Array methods

In [ ]:
import numpy as np

my_array = np.array([0, 1, 2, 3, 4, 8])
print(f"My original array: {my_array}\n")

# Add values to the end of the array
numbers_to_append = [9, 10]
my_array_appended = np.append(my_array, numbers_to_append)
print(f"My appended array: {my_array_appended}\n")

# Insert values in a specific index
index = 5
numbers_to_insert = [5, 6, 7]
my_array_inserted = np.insert(my_array, index, numbers_to_insert)
print(f"My inserted array in index {index}: {my_array_inserted}\n")

# Delete values of a specific index
index = 5
my_array_deleted = np.delete(my_array, index)
print(f"My deleted array in index {index}: {my_array_deleted}")

My original array: [0 1 2 3 4 8]

My appended array: [ 0  1  2  3  4  8  9 10]

My inserted array in index 5: [0 1 2 3 4 5 6 7 8]

My deleted array in index 5: [0 1 2 3 4]


In [ ]:
import numpy as np

# Create a 2D array
matrix_1 = np.array([[1, 2,3, 4],
                     [5, 6, 7, 8],])
matrix_2 = np.array([[9, 10, 11, 12],
                     [13, 14, 15, 16]])
print(f"Matrix 1: \n{matrix_1}")
print(f"Matrix 2: \n{matrix_2}\n")


# Concatenate two arrays row-wise
concatenated_row_wise = np.concatenate((matrix_1, matrix_2), axis=0) # or you can use `.vstack((matrix_1, matrix_2))`
print(f"Concatenated arrays row-wise: \n{concatenated_row_wise}\n")

# Concatenate two arrays column-wise
concatenated_column_wise = np.concatenate((matrix_1, matrix_2), axis=1) # or you can use `.hstack((matrix_1, matrix_2))`
print(f"Concatenated arrays column-wise: \n{concatenated_column_wise}\n")

# Add a new dimension after concatenating using `.stack()`
stacked_matrix = np.stack((matrix_1, matrix_2))
print(f"Stacked arrays: \n{stacked_matrix}\n")

# Split array
num_arrays_to_split = 2 # Amount of arrays we want to split
splitted_matrix_row_wise = np.split(concatenated_row_wise, num_arrays_to_split, axis=0) # means split the array into 2 arrays row-wise(axis=0)
splitted_matrix_column_wise = np.split(concatenated_row_wise, num_arrays_to_split, axis=1) # means split the array into 2 arrays column-wise(axis=1)
print(f"Array before splitting: \n{concatenated_row_wise}")
print(f"Array after splitting row-wise: \n{splitted_matrix_row_wise}")
# print(f"Array after splitting column-wise: \n{splitted_matrix_column_wise}")

Matrix 1: 
[[1 2 3 4]
 [5 6 7 8]]
Matrix 2: 
[[ 9 10 11 12]
 [13 14 15 16]]

Concatenated arrays row-wise: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Concatenated arrays column-wise: 
[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]

Stacked arrays: 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]

Array before splitting: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Array after splitting row-wise: 
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


#### Checking the properties within the array
#### But before that, let's try to use `np.random.seed()` which basically lets us have the same random values for you and me.

In [ ]:
np.random.seed(42)

random_array = np.random.rand(5,2)
print(f"Random array: \n{random_array}\n")

# Check the shape of my array
random_array_shape = random_array.shape # We use `.shape` to access the values of the attribute
print(f"Random array shape: {random_array_shape}")

# Check how many dimensions a certain array has
random_array_ndimensions = random_array.ndim
print(f"Random array number of dimensions: {random_array_ndimensions}")

# Check what datatype an array has
random_array_dtype = random_array.dtype
print(f"Random array datatype: {random_array_dtype}")

# Check the total size an array has
random_array_size = random_array.size
print(f"Random array size: {random_array_size}")

Random array: 
[[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]
 [0.05808361 0.86617615]
 [0.60111501 0.70807258]]

Random array shape: (5, 2)
Random array number of dimensions: 2
Random array datatype: float64
Random array size: 10


#### Accessing elements within a NumPy array

In [ ]:
np.random.seed(42)

upper_bound = 20 # Create an upper bound

random_array = np.random.randint(upper_bound, size=(5,5)) # Create a 5x5 array with upperbound of 20
print(f"Random array: \n{random_array}\n")

# Get the element of the array in the 1st row and 3rd column. Keep in mind that index always starts with 0
row = 0 # 1st row
column = 2 # 3rd column
element = random_array[row, column]
print(f"Element in the row {row} and column {column}: {element}\n")


# What if I want to get/access all the elements within a row(or column) in our array?
row = 0 # 1st row
column = 2 # 3rd column
elements_in_row = random_array[row, :] # means get all the elements in that specific row
print(f"Elements in row {row}: {elements_in_row}")
elements_in_column = random_array[:, column] # means to get all the elements in that specific column
print(f"Elements in column {column}: {elements_in_column}\n")


# What if I want to get all the elements from a specific row (or column) upto another?
lower_row = 1 # 2nd row
upper_row = 4 # 5th row
lower_column = 1 # 2nd column
upper_column = 4 # 5th column
elements_within_rows = random_array[lower_row:upper_row, :] # Means get all the elements from a specific row i up to row j-1
print(f"Elements from row {lower_row} to row {upper_row}-1: \n{elements_within_rows}")
elements_within_columns = random_array[:, lower_column:upper_column] # Means get all the elements from a specific row i up to row j-1
print(f"Elements from column {lower_column} to column {upper_column}-1: \n{elements_within_columns}")


Random array: 
[[ 6 19 14 10  7]
 [ 6 18 10 10  3]
 [ 7  2  1 11  5]
 [ 1  0 11 11 16]
 [ 9 15 14 14 18]]

Element in the row 0 and column 2: 14

Elements in row 0: [ 6 19 14 10  7]
Elements in column 2: [14 10  1 11 14]

Elements from row 1 to row 4-1: 
[[ 6 18 10 10  3]
 [ 7  2  1 11  5]
 [ 1  0 11 11 16]]
Elements from column 1 to column 4-1: 
[[19 14 10]
 [18 10 10]
 [ 2  1 11]
 [ 0 11 11]
 [15 14 14]]


#### Manipulating numpy arrays

In [ ]:
import numpy as np

upper_bound = 20
random_array = np.random.randint(upper_bound, size=(2, 9))

# As you will see after printing this variable, you will receive a tuple (2, 9) that represents the size of each dimensions
print(f"Random array: \n{random_array}")
print(f"Random array shape: {random_array_shape}\n\n")


# What if I want to swap those two dimensions sizes, for example, from (9, 2) to (2, 9)? Use `.transpose()`
random_array_transposed = random_array.transpose(1, 0) # the arguments within `.transpose(1, 0)` represents the index position of the value of each dimensions size in the shape tuple
random_array_transposed_shape = random_array_transposed.shape
print(f"Random array before transposing: \n{random_array}")
print(f"Random array after transposing: \n{random_array_transposed}")
print(f"Random array transposed shape: {random_array_transposed_shape}\n")


# Reshape an array, for example from (9,2) into (1, 18) or (3, 6) or (6, 3) or (2, 9) as long as the product of each dimension size is equal to the total size, which in this case is 18
random_array_reshaped = random_array.reshape(18, 1)
random_array_reshaped_shape = random_array_reshaped.shape
print(f"Random array before reshaping: \n{random_array}")
print(f"Random array after reshaping: \n{random_array_reshaped}")
print(f"Random reshaped shape: {random_array_reshaped_shape}\n")
# But if you don't want to use `.reshape()` because you want to assign it immediately to the variable, you can use `.resize()`


# What if I want to get the 1D version of my original array? You can use `.flatten()`
random_array_flattened = random_array.flatten()
print(f"Random array before flattening: \n{random_array}")
print(f"Random array after flattening: {random_array_flattened}")



Random array: 
[[ 0  0 18  1 11  5  3 10 16]
 [ 5  4 19  1  5 10 15 15  0]]
Random array shape: (5, 2)


Random array before transposing: 
[[ 0  0 18  1 11  5  3 10 16]
 [ 5  4 19  1  5 10 15 15  0]]
Random array after transposing: 
[[ 0  5]
 [ 0  4]
 [18 19]
 [ 1  1]
 [11  5]
 [ 5 10]
 [ 3 15]
 [10 15]
 [16  0]]
Random array transposed shape: (9, 2)

Random array before reshaping: 
[[ 0  0 18  1 11  5  3 10 16]
 [ 5  4 19  1  5 10 15 15  0]]
Random array after reshaping: 
[[ 0]
 [ 0]
 [18]
 [ 1]
 [11]
 [ 5]
 [ 3]
 [10]
 [16]
 [ 5]
 [ 4]
 [19]
 [ 1]
 [ 5]
 [10]
 [15]
 [15]
 [ 0]]
Random reshaped shape: (18, 1)

Random array before flattening: 
[[ 0  0 18  1 11  5  3 10 16]
 [ 5  4 19  1  5 10 15 15  0]]
Random array after flattening: [ 0  0 18  1 11  5  3 10 16  5  4 19  1  5 10 15 15  0]


#### Trying out Statistics and other operations

In [ ]:
np.random.seed(42)
upper_bound = 20
random_array = np.random.randint(upper_bound, size=(2, 5))
print(f"My array: \n{random_array}\n")

# Sort the array
random_array_sorted = np.sort(random_array)
print(f"Sorted array: \n{random_array_sorted}\n")

# Finding the smallest value of the entire array
smallest_value = np.min(random_array)
print(f"Smallest value: {smallest_value}")
# Finding the smallest value of each row, or in this case, axis=1
smallest_value_row = np.min(random_array, axis=1)
print(f"Smallest value within each row: {smallest_value_row}")
# Finding the smallest value of each column, or in this case, axis=0
smallest_value_column = np.min(random_array, axis=0)
print(f"Smallest value within each column: {smallest_value_column}\n")

# Finding the largest value of the entire array
largest_value = np.max(random_array)
print(f"Largest value: {largest_value}")
# Finding the largest value of each row, or in this case, axis=1
largest_value_row = np.max(random_array, axis=1)
print(f"Largest value within each row: {largest_value_row}")
# Finding the largest value of each column, or in this case, axis=0
largest_value_column = np.max(random_array, axis=0)
print(f"Largest value within each column: {largest_value_column}\n")

# Get the sum of the entire array
total_sum = random_array.sum()
print(f"The sum of the entire array is: {total_sum}")
# Get the sum of every element in each row (axis=1)
row_sum = random_array.sum(axis=1)
print(f"The sum of each row is: {row_sum}")
# Get the sum of every element in each column (axis=0)
column_sum = random_array.sum(axis=0)
print(f"The sum of each column is: {column_sum}\n")

# Find the mean, median, mode, and standard deviation of the entire array
mean = random_array.mean()
median = np.median(random_array)
std = np.std(random_array)
print(f"The mean of the array is: {mean}")
print(f"The median of the array is: {median}")
print(f"The standard deviation of the array is: {std}")

"""
P.S. There is not built-in function for mode in NumPy, so if you want to get the mode of an array you may use the code provided below, but you may use other methods if you wish.


unique_elements, counts = np.unique(random_array, return_counts=True)
mode_index = np.argmax(counts)
mode = unique_elements[mode_index]

"""

My array: 
[[ 6 19 14 10  7]
 [ 6 18 10 10  3]]

Sorted array: 
[[ 6  7 10 14 19]
 [ 3  6 10 10 18]]

Smallest value: 3
Smallest value within each row: [6 3]
Smallest value within each column: [ 6 18 10 10  3]

Largest value: 19
Largest value within each row: [19 18]
Largest value within each column: [ 6 19 14 10  7]

The sum of the entire array is: 103
The sum of each row is: [56 47]
The sum of each column is: [12 37 24 20 10]

The mean of the array is: 10.3
The median of the array is: 10.0
The standard deviation of the array is: 5.000999900019995


Some math operations using arrays...

In [ ]:
# Create two arrays
np.random.seed(42)
upper_bound = 5
array_1 = np.random.randint(5, size=(1, 6))
array_2 = np.random.randint(5, size=(1, 6))
print(f"First array:  {array_1}")
print(f"Second array: {array_2}\n")

# Add two arrays
array_sum = array_1 + array_2
print(f"The sum of the two arrays is: {array_sum}")

# Subtract two arrays
array_difference = array_1 - array_2
print(f"The difference of the two arrays is: {array_difference}")

# Multiply two arrays
array_product = array_1 + array_2
print(f"The product of the two arrays is: {array_product}")

# Divide two arrays
array_quotient = array_1 / array_2
print(f"The quotient of the two arrays is: {array_quotient}\n")

# Matrix multiply two arrays. Make sure that each shape of the two arrays is in the form of mxn * nxp = mxp, for example: (2,5) and (5,4) results in shape (2, 4)
print(f"Array 1 shape: {array_1.shape}")
print(f"Array 2 shape: {array_2.shape}")
array_2_transposed = array_2.transpose(1, 0)  # Since the shape is mismatched we perform a transpose so that our array_2 is converted from (1, 6) to (6, 1)
print(f"Array 2 transposed shape: {array_2_transposed.shape}")
matmul_product = np.matmul(array_1, array_2_transposed)
print(f"The matrix multiplication of the two arrays {array_1.shape}*{array_2_transposed.shape} is: {matmul_product}")


First array:  [[3 4 2 4 4 1]]
Second array: [[2 2 2 4 3 2]]

The sum of the two arrays is: [[5 6 4 8 7 3]]
The difference of the two arrays is: [[ 1  2  0  0  1 -1]]
The product of the two arrays is: [[5 6 4 8 7 3]]
The quotient of the two arrays is: [[1.5        2.         1.         1.         1.33333333 0.5       ]]

Array 1 shape: (1, 6)
Array 2 shape: (1, 6)
Array 2 transposed shape: (6, 1)
The matrix multiplication of the two arrays (1, 6)*(6, 1) is: [[48]]
